export default {
    homeScreen_header:"Welcome",
    homeScreen_sub_header:"Here you can find the best updated articels around US",
    homeScreen_favorite_btn:'FAVORITES',
    homeScreen_articles_btn:'ARTICLES',
    tab_homeScreen:"HOME",
    tab_favoriteScreen:"FAVORITES",
    tab_categories:"CATEGORIES",
    articlesList_header:"List of articles",
    card_go_to_article:"press to read the acticle",
    modal_header:"Please sign in with your google acount to enable you save your favorites articles",
    modal_addToFavorite_access:"Please sign in to save your favorites articles",
    modal_addToFavorite_btn:"Go to loggin screen",
    cancel:"Cancel",
    addToFavorites:"Add to favorite",
    removeFromFavorites:"Remove from favorite",
    favoritesEmpty:"Your list is empty... to add an acticle go to category section",
    logOut:"Disconnect",
    dashboardHeader:"Dashboard data:",
    dashboard_favorite_title:"Sum of favorite articles",
    toast_deleteArticle:"You Article has been removed",
    toast_addArticle:"You Article has been added",
}